import { notificationSchema } from "./types/notification-types"

const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

const notificationsData = [
  {
    id: "NOTIF-001",
    type: "task_assigned" as const,
    title: "New task assigned",
    message: "You have been assigned to 'Implement user authentication with OAuth 2.0'",
    taskId: "TASK-1001",
    taskTitle: "Implement user authentication with OAuth 2.0",
    senderId: "USER-001",
    senderName: "Admin",
    recipientId: "USER-002",
    read: false,
    createdAt: hoursAgo(1),
  },
  {
    id: "NOTIF-002",
    type: "task_due_soon" as const,
    title: "Task due soon",
    message: "'Fix memory leak in dashboard component' is due in 2 days",
    taskId: "TASK-1002",
    taskTitle: "Fix memory leak in dashboard component causing browser slowdown",
    recipientId: "USER-002",
    read: false,
    createdAt: hoursAgo(3),
  },
  {
    id: "NOTIF-003",
    type: "task_overdue" as const,
    title: "Task overdue",
    message: "'Update API documentation for v2 endpoints' was due 3 days ago",
    taskId: "TASK-1003",
    taskTitle: "Update API documentation for v2 endpoints",
    recipientId: "USER-002",
    read: false,
    createdAt: hoursAgo(5),
  },
  {
    id: "NOTIF-004",
    type: "task_status_changed" as const,
    title: "Task status updated",
    message: "'Implement user authentication with OAuth 2.0' changed from In Progress to Done",
    taskId: "TASK-1001",
    taskTitle: "Implement user authentication with OAuth 2.0",
    senderId: "USER-001",
    senderName: "Admin",
    recipientId: "USER-003",
    read: true,
    createdAt: hoursAgo(8),
  },
  {
    id: "NOTIF-005",
    type: "comment_added" as const,
    title: "New comment",
    message: "Admin commented on 'Add dark mode support for all UI components': 'Great progress!'",
    taskId: "TASK-1004",
    taskTitle: "Add dark mode support for all UI components",
    senderId: "USER-001",
    senderName: "Admin",
    recipientId: "USER-002",
    read: true,
    createdAt: hoursAgo(12),
  },
  {
    id: "NOTIF-006",
    type: "mention" as const,
    title: "You were mentioned",
    message: "@you in 'Fix login page not redirecting after successful authentication'",
    taskId: "TASK-1005",
    taskTitle: "Resolve login page not redirecting after successful authentication",
    senderId: "USER-003",
    senderName: "Manager",
    recipientId: "USER-002",
    read: false,
    createdAt: daysAgo(1),
  },
  {
    id: "NOTIF-007",
    type: "task_assigned" as const,
    title: "New task assigned",
    message: "You have been assigned to 'Add export functionality for analytics reports'",
    taskId: "TASK-1016",
    taskTitle: "Add export functionality for analytics reports",
    senderId: "USER-003",
    senderName: "Manager",
    recipientId: "USER-002",
    read: true,
    createdAt: daysAgo(2),
  },
  {
    id: "NOTIF-008",
    type: "task_due_soon" as const,
    title: "Task due soon",
    message: "'Implement two-factor authentication option' is due tomorrow",
    taskId: "TASK-1028",
    taskTitle: "Implement two-factor authentication option",
    recipientId: "USER-002",
    read: false,
    createdAt: daysAgo(1),
  },
  {
    id: "NOTIF-009",
    type: "task_status_changed" as const,
    title: "Task status updated",
    message: "'Add export functionality for analytics reports' changed from To Do to Done",
    taskId: "TASK-1016",
    taskTitle: "Add export functionality for analytics reports",
    senderId: "USER-002",
    senderName: "User",
    recipientId: "USER-003",
    read: false,
    createdAt: daysAgo(3),
  },
  {
    id: "NOTIF-010",
    type: "task_overdue" as const,
    title: "Task overdue",
    message: "'Create onboarding tutorial for new users' was due 5 days ago",
    taskId: "TASK-1006",
    taskTitle: "Create onboarding tutorial for new users",
    recipientId: "USER-002",
    read: true,
    createdAt: daysAgo(5),
  },
]

export const notificationMockData = notificationSchema.array().parse(notificationsData)
