import { documentSchema } from "./types/document-types"

const documentsData = [
  {
    id: "DOC-1001",
    name: "Q2 Product Roadmap.pdf",
    url: "https://example.com/docs/roadmap-q2.pdf",
    type: "application/pdf",
    size: 2457600,
    taskId: "TASK-1010",
    taskTitle: "Implement real-time notifications using WebSockets",
    teamId: "team-001",
    teamName: "Frontend Team",
    uploadedBy: "admin-001",
    uploadedByName: "Admin User",
    createdAt: "2026-05-01T10:00:00Z",
  },
  {
    id: "DOC-1002",
    name: "API Documentation v2.docx",
    url: "https://example.com/docs/api-docs-v2.docx",
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 1024000,
    taskId: "TASK-1003",
    taskTitle: "Update API documentation for v2 endpoints",
    uploadedBy: "user-001",
    uploadedByName: "John Developer",
    createdAt: "2026-05-03T14:30:00Z",
  },
  {
    id: "DOC-1003",
    name: "Design System Guidelines.pdf",
    url: "https://example.com/docs/design-system.pdf",
    type: "application/pdf",
    size: 3145728,
    teamId: "team-001",
    teamName: "Frontend Team",
    uploadedBy: "user-002",
    uploadedByName: "Jane Engineer",
    createdAt: "2026-05-05T09:15:00Z",
  },
  {
    id: "DOC-1004",
    name: "Meeting Notes - Sprint Planning.txt",
    url: "https://example.com/docs/meeting-notes.txt",
    type: "text/plain",
    size: 8192,
    taskId: "TASK-1001",
    taskTitle: "Implement user authentication with OAuth 2.0",
    uploadedBy: "user-001",
    uploadedByName: "John Developer",
    createdAt: "2026-05-10T11:00:00Z",
  },
  {
    id: "DOC-1005",
    name: "Sprint Review Presentation.pptx",
    url: "https://example.com/docs/sprint-review.pptx",
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 5242880,
    uploadedBy: "admin-001",
    uploadedByName: "Admin User",
    createdAt: "2026-05-08T16:00:00Z",
  },
]

export const documentMockData = documentSchema.array().parse(documentsData)
